import { describe, expect, it } from "vitest";
import { parseZapiWebhookPayload, planZapiWebhookAction } from "./ingest";
import { hasZapiReactionPayload, isLegacyZapiReactionBody } from "./webhook-event";

describe("parseZapiWebhookPayload media", () => {
  const messageBase = {
    type: "ReceivedCallback",
    phone: "5521964011406",
    messageId: "message-with-media",
  };

  it("does not stop at an empty root image when the nested message has the URL", () => {
    const parsed = parseZapiWebhookPayload({
      ...messageBase,
      image: { caption: "Imagem recebida" },
      message: {
        imageMessage: {
          imageUrl: "https://example.test/photo.jpg",
          mimetype: "image/jpeg",
        },
      },
    });

    expect(parsed?.media).toEqual({
      kind: "image",
      url: "https://example.test/photo.jpg",
      mimeType: "image/jpeg",
      fileName: null,
    });
  });

  it("imports a document URL nested in a view-once wrapper", () => {
    const parsed = parseZapiWebhookPayload({
      ...messageBase,
      document: { fileName: "proposta.pdf" },
      message: {
        viewOnceMessageV2: {
          documentMessage: {
            documentUrl: "https://example.test/proposta.pdf",
            mimetype: "application/pdf",
            fileName: "proposta.pdf",
          },
        },
      },
    });

    expect(parsed?.media).toEqual({
      kind: "document",
      url: "https://example.test/proposta.pdf",
      mimeType: "application/pdf",
      fileName: "proposta.pdf",
    });
  });

  it("recognizes instant video and GIF payloads as playable video", () => {
    const ptv = parseZapiWebhookPayload({
      ...messageBase,
      ptv: { videoUrl: "https://example.test/round.mp4", mimetype: "video/mp4" },
    });
    const gif = parseZapiWebhookPayload({
      ...messageBase,
      gif: { videoUrl: "https://example.test/animation.mp4", mimetype: "video/mp4" },
    });

    expect(ptv?.media?.kind).toBe("video");
    expect(gif?.media?.kind).toBe("video");
  });
});

describe("parseZapiWebhookPayload calls", () => {
  const callBase = {
    type: "ReceivedCallback",
    phone: "5511958761204",
    callId: "CALL-123",
    messageId: "call-message-1",
    fromMe: false,
  };

  it("recognizes a voice call while it is ringing", () => {
    const parsed = parseZapiWebhookPayload({
      ...callBase,
      notification: "CALL_VOICE",
    });

    expect(parsed?.callEvent).toEqual({ status: "ringing", callId: "CALL-123" });
  });

  it("recognizes missed voice and video calls", () => {
    const voice = parseZapiWebhookPayload({
      ...callBase,
      notification: "CALL_MISSED_VOICE",
    });
    const video = parseZapiWebhookPayload({
      ...callBase,
      notification: "CALL_MISSED_VIDEO",
    });

    expect(voice?.callEvent?.status).toBe("missed_voice");
    expect(video?.callEvent?.status).toBe("missed_video");
  });
});

describe("hasZapiReactionPayload", () => {
  it("ignores a flat Z-API reaction instead of creating a chat bubble", () => {
    expect(
      hasZapiReactionPayload({
        type: "DeliveryCallback",
        phone: "5511958761204",
        reaction: { text: "❤️", messageId: "target-message" },
      }),
    ).toBe(true);
  });

  it("ignores reactions nested in common WhatsApp message wrappers", () => {
    expect(
      hasZapiReactionPayload({
        type: "ReceivedCallback",
        data: {
          key: { remoteJid: "5511958761204@s.whatsapp.net" },
          message: {
            ephemeralMessage: {
              message: {
                reactionMessage: { text: "❤️", key: { id: "target-message" } },
              },
            },
          },
        },
      }),
    ).toBe(true);
  });

  it("continues parsing ordinary messages", () => {
    expect(
      hasZapiReactionPayload({
        type: "ReceivedCallback",
        phone: "5511958761204",
        text: { message: "50g" },
      }),
    ).toBe(false);
  });
});

describe("isLegacyZapiReactionBody", () => {
  it("recognizes reaction bubbles previously generated by the CRM", () => {
    expect(isLegacyZapiReactionBody("[Reação]")).toBe(true);
    expect(isLegacyZapiReactionBody("Reação: ❤️")).toBe(true);
    expect(isLegacyZapiReactionBody("Hoje você trabalha com qual gramatura de pão?")).toBe(false);
  });
});

describe("planZapiWebhookAction deleted messages", () => {
  it("ignores the Z-API deleted-conversation marker", () => {
    expect(
      planZapiWebhookAction({
        type: "ReceivedCallback",
        phone: "5511958761204",
        messageId: "deleted-marker",
        text: { message: "CONVERSA APAGADA" },
      }),
    ).toEqual({ action: "skip", reason: "deleted_message_event" });
  });

  it("ignores a Baileys revoke protocol event", () => {
    expect(
      planZapiWebhookAction({
        type: "ReceivedCallback",
        data: {
          key: { remoteJid: "5511958761204@s.whatsapp.net" },
          message: { protocolMessage: { type: 0, key: { id: "original-message" } } },
        },
      }),
    ).toEqual({ action: "skip", reason: "deleted_message_event" });
  });

  it("keeps ordinary messages that merely mention deleting something", () => {
    expect(
      planZapiWebhookAction({
        type: "ReceivedCallback",
        phone: "5511958761204",
        text: { message: "Pode apagar o pedido duplicado?" },
      }),
    ).toEqual({ action: "parse" });
  });
});

describe("parseZapiWebhookPayload status callbacks", () => {
  it("identifies a status callback with phone as a technical event", () => {
    const parsed = parseZapiWebhookPayload({
      type: "MessageStatusCallback",
      phone: "5511958761204",
      messageId: "status-only-message",
      status: "READ",
    });

    expect(parsed?.eventType).toBe("MessageStatusCallback");
    expect(parsed?.messageStatus).toBe("read");
    expect(parsed?.body).toBeNull();
  });
});
